package PaySlipSystem.Controller;
/**
 * This class provide various method in order to handle the input and output of the
 * data in various format and objects. This class is responsible for the converting the
 * input.csv and extracting information in order to generate payslip object. This class also
 * has method that handle writing the data to payslipreport.csv for future use. There is
 * method called createIndividualTaxReport() that handles creating payslip in the format of
 * username.txt using all the information entered by the user in terminal.
 */

import PaySlipSystem.Model.Employee;
import PaySlipSystem.Model.PaySlip;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Scanner;

public class DataInputOutputController {


    /**
     * This method read the content of the paySlipList created by readInputData and convert it into payslipreport.csv
     *
     */
    public  void updatePaySlipReportFile(ArrayList<PaySlip> paySlipList) {
        try{

            PrintWriter outFile = new PrintWriter("payslipreport.csv");
            for (int i = 0; i < paySlipList.size(); i++ ){
                if(i == 0){
                    System.out.println("\nOutput data are as follows\n" +
                            "Name,Pay Period,Gross Income,Income Tax, Net Income, Super");
                    outFile.println("Name,Pay Period,Gross Income,Income Tax, Net Income, Super");
                    outFile.print(paySlipList.get(i));
                    System.out.println(paySlipList.get(i));
                }
                else{
                    outFile.print("\n"+paySlipList.get(i));
                    System.out.println(paySlipList.get(i));
                }
            }
            outFile.close();
        }
        catch(Exception ex){
            System.err.println("Something went wrong");
        }
    }

    /**
     * This method take paySlip information that is generated by the information provided by the user
     * and convert into a preformatted text file so that it can be easily shared with the employee.
     * @param paySlip
     */
    public static void createIndividualTaxReport (PaySlip paySlip){
       Employee employee = paySlip.getEmployee();
       String firstName = employee.getFirstName();
       String lastName  = employee.getLastName();
       int grossIncome  = paySlip.getGrossIncome();
       int incomeTax    = paySlip.getIncomeTax();
       int netIncome    = paySlip.getNetIncome();
       int superAmount  = paySlip.getSuperAmount();
       String payPeriod = paySlip.getPayPeriod();
        try{
            String fileName = firstName+lastName+".txt";
            PrintWriter outFile = new PrintWriter(fileName);
            outFile.println("My Company " +
                    "\nAddress\n" +
                    "123 Melbourne St\n" +
                    "Melbourne\n" +
                    "ABN : 123456789\n\n" +
                    "-------------------\n" +
                    "Employee Detail\n" +
                    firstName + " "+ lastName+"\n" +
                    "-------------------\n" +
                    "\n" +
                    "Pay Period:\t"+ payPeriod +"\n" +
                    "\n" +
                    "Gross Pay:\t"+ grossIncome + "\n" +
                    "Tax:\t\t"+ incomeTax+"\n" +
                    "\n" +
                    "Super:\t\t" + superAmount+ "\n" +
                    "\n" +
                    "Net Income:\t" + netIncome);
            outFile.close();
        }
        catch(Exception ex){
            System.err.println("Something went wrong");
        }
    }
}
